server:
  port: 8080
spring:
  application:
    name: "JavaBatch"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  region: "us-east-1"
adapter:
  restconsumer:
    url: "http://54.221.139.10:3000/0"
batch:
  operation: "http"